### ISSUE TITLE
Matter.js circle physics don't work as expected

### ISSUE THREAD

**Issue by jay-jlm** [mikewesthad/phaser-3-tilemap-blog-posts#1] opened 2018-09-16 01:19 UTC
https://codesandbox.io/s/0v1k9xk7j0

Circles never quite stop moving and their physics don't seem to work right (sometimes they stay glued to other circles without proper support and without falling over)

Setting friction to 0 seems to have some effect on this behavior but does not completely fix it.

**Comment by mikewesthad** [comment] 2018-09-16 02:37
Hiya - are you following along with the blog post? This snippet in question is pulled from partway through the article where the tile bodies have yet to be mapped, which is described [here](https://itnext.io/modular-game-worlds-in-phaser-3-tilemaps-4-meet-matter-js-abf4dfa65ca1#3c2a). The article then describes how to map tile bodies to get collisions that match the tile shapes.

**Comment by jay-jlm** [comment] 2018-09-16 04:07
Hi, thanks for the quick response Mike, love your tutorials!
I went to the link you provided and tested with the [example](https://www.mikewesthad.com/phaser-3-tilemap-blog-posts/post-4/03-mapping-tiles/) that is listed in the very end of the article and I still get the same results.
See a video capture here:  http://nimb.ws/ikRH2w

**Comment by jay-jlm** [comment] 2018-09-16 04:34
Did a bit more investigation. I can reproduce this problem in other demos such as this one:
labs.phaser.io/edit.html?src=src\game%20objects\tilemap\collision\matter%20platformer%20with%20wall%20jumping.js

This is the code that I used some circles at runtime (visually is still a square block thou):
```
    this.input.on("pointerdown", () => {
      const worldPoint = this.input.activePointer.positionToCamera(this.cameras.main)
        const x = worldPoint.x 
        const y = worldPoint.y 
        const newImg = this.matter.add.image(x, y, "box")
        newImg.setCircle(newImg.width / 2, { restitution: 0.9, friction: 0})
        .setScale(0.5)
      
    })
```
Playing with the restitution values does affect the intensity of the problem. restitution=1 is the worst but once I get down to 0.6 it looks pretty much fixed.

**Updated:**
After further investigation I'm almost convinced it's a limitation of Matter.js's own circle collision algo.
As you can see at the link below, at resolution 0.6 the collision artifacts are barely noticeable, by 0.8 I can get stack of balls to jitter for a few seconds before the it stabilizes and by the time I get to 0.95 the stack is unstable for as long as I was able to wait.
https://codesandbox.io/s/n0jjx07nwl   (mouse down to add more balls, test with at least 75% full)

**Comment by mikewesthad** [comment] 2018-09-16 15:53
Ah, I thought that when you said:

> "sometimes they stay glued to other circles without proper support and without falling over" 

you were referring to the fact that they hung in the air over some of the tiles (e.g. lava and sloped tiles) since that demo doesn't have tile bodies yet. Thanks for clarifying.

The root of the issue is probably with the restitution resolution itself, since the same issue would occur if you use bouncy rectangular bodies. Have you tried adjusting the quality of the simulation via the engine props like [`positionIterations`](http://brm.io/matter-js/docs/classes/Engine.html#property_positionIterations), or increasing the `slop` on the bodies?

**Comment by mikewesthad** [comment] 2018-10-13 12:47
I'm going to close this issue. This is a matter-specific problem that might be mitigated by diving into matter configuration that's beyond the scope of what I want to cover in this tutorial series. Thanks for bringing it to my attention.

**Closed as completed by mikewesthad** 2018-10-13 12:47 UTC

**Comment by likeavenus** [comment] 2024-04-24 11:54
same issue
